# Generated by Django 4.0.3 on 2022-03-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32)),
                ('question', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
    ]
